export {
  DEFAULT_METRICS_EXPORTER,
  DEFAULT_PROMETHEUS_HOST,
  DEFAULT_PROMETHEUS_PORT,
  DEFAULT_SERVICE_NAME,
  DEFAULT_SERVICE_VERSION,
  OTEL_EXPORTER_OTLP_ENDPOINT_ENV,
  OTEL_EXPORTER_OTLP_HEADERS_ENV,
  OTEL_EXPORTER_OTLP_PROTOCOL_ENV,
  OTEL_EXPORTER_PROMETHEUS_HOST_ENV,
  OTEL_EXPORTER_PROMETHEUS_PORT_ENV,
  OTEL_METRICS_EXPORTER_ENV,
  OTEL_SERVICE_NAME_ENV,
  OTEL_SERVICE_VERSION_ENV,
  TELEMETRY_ENABLED_ENV,
  loadTelemetryConfigFromEnv,
} from './config.js';
export type { MetricsExporter, TelemetryConfig } from './config.js';

export {
  TELEMETRY_INSTRUMENTATION_NAME,
  TelemetryProvider,
  createTelemetryProvider,
} from './provider.js';
export type { CreateTelemetryProviderOptions } from './provider.js';

export {
  ATTR_CONTEXT_ID,
  ATTR_JSONRPC_METHOD,
  ATTR_JSONRPC_REQUEST_ID,
  ATTR_TASK_ID,
  DEFAULT_JSONRPC_SPAN_KIND,
  DEFAULT_LLM_SPAN_KIND,
  DEFAULT_TASK_SPAN_KIND,
  SPAN_NAME_BACKGROUND_TASK,
  SPAN_NAME_JSONRPC_REQUEST,
  SPAN_NAME_LLM_COMPLETION,
  SPAN_NAME_STREAMING_TASK,
  recordSpanError,
  setSpanAttributes,
} from './spans.js';
